file main.elf
target remote :3333
set logging file gdb.log
set logging overwrite on
set logging on

b main
b SVC_Handler
b fork
b getpid
b serialout
b serialin
b greeting
c
display /x $r0
display /x $r7
display /x $lr
display /x $sp
display /x $pc
display /x *tasks[2].stack
display /x *tasks[3].stack
display /x *tasks[4].stack
display /x tasks
display task_count
display current_task
info address first
